DoTheZ-Team/post-service

src/main/java/com/justdo/plug/post/domain/photo/Photo.java, src/main/java/com/justdo/plug/post/domain/photo/service/PhotoService.java, src/main/java/com/justdo/plug/post/domain/post/Post.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostRequestDto.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostResponseDto.java, src/main/java/com/justdo/plug/post/domain/post/repository/PostRepository.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/domain/posthashtag/service/PostHashtagService.java
- Convention Camel Case로 수정
- [이슈 참고]
- 
- close #5
=> PLUG-160 : chore - Convention Camel Case로 수정

build.gradle, src/main/java/com/justdo/plug/post/PostApplication.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PreviewResponse.java, src/main/java/com/justdo/plug/post/domain/post/repository/PostRepository.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/global/config/SwaggerConfig.java, src/main/resources/application.yml, src/test/java/com/justdo/plug/post/PostApplicationTests.java
- Post의 preview 목록 조회 API 구현
- 내가 구독한 블로그의 정보 조회
- 나를 구독한 블로그의 정보 조회
- Intellij 단축키 command + option + L / control + option + o 버튼 눌러서 안쓰는 import 삭제랑 자동 정렬 해주시면 좋을 거 같습니다. @anselmo228 
- ⭐ 포스트 이미지 저장이랑 메인 이미지 정하면 될 것 같습니다.
- close #
=> GLUE-252 🔥 : Feat: Post의 preview 목록 조회 API 구현

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
- Elastic Search 검색엔진 구현
- 특정 Keyword 입력 하면 그 keyword를 내포한 모든 post Id 를 반환 해줌
- 
- close #
=> GLUE-269 : ElasticSearch Post 게시글 검색엔진 구현

build.gradle, src/main/java/com/justdo/plug/post/PostApplication.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostSearchDTO.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/elastic/PostDocument.java, src/main/java/com/justdo/plug/post/elastic/PostElasticsearchRepository.java, src/main/java/com/justdo/plug/post/global/config/ElasticSearchConfig.java
- elastic document 및 save 구현
-
-
- close #
=> Feat : elastic document 및 save 구현

build.gradle, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostSearchDTO.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/elastic/PostDocument.java, src/main/java/com/justdo/plug/post/elastic/PostElasticsearchRepository.java, src/main/resources/application.yml
- 검색결과 반환 값 지정
[게시글 검색 결과]
[검색결과에 대한 블로그 아이디, 게시글 아이디 리스트]
- Elastic Search 저장은 현겸이 방식대로 ElasticSearchRepository에 저장
- 검색엔진은 기존 방법 대로 ES에 API Query로 해결
-
- close #
=> GLUE-269 : feat: ElasticSearch 검색결과 형식 지정

src/main/java/com/justdo/plug/post/domain/photo/repository/PhotoRepository.java, src/main/java/com/justdo/plug/post/domain/post/repository/PostRepository.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
-  Merge 하면서 없어진 코드 수정
-
-
- close #
=> fix: Merge 하면서 없어진 코드 수정

src/main/java/com/justdo/plug/post/domain/like/Like.java, src/main/java/com/justdo/plug/post/domain/liked/Liked.java, src/main/java/com/justdo/plug/post/domain/liked/repository/LikedRepository.java, src/main/java/com/justdo/plug/post/domain/liked/service/LikedService.java, src/main/java/com/justdo/plug/post/domain/post/Post.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/repository/PostRepository.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
- 게시글 좋아요 등록 
[Postman 결과]
[Post table 적용결과]
[Liked table 적용결과]
-
-
- close #
=> GLUE-89 : feat - 게시글 좋아요 등록

src/main/java/com/justdo/plug/post/PostApplication.java, src/main/java/com/justdo/plug/post/domain/comment/controller/CommentController.java, src/main/java/com/justdo/plug/post/domain/comment/dto/CommentResponse.java, src/main/java/com/justdo/plug/post/domain/likes/controller/LikesController.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PreviewResponse.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/global/config/SwaggerConfig.java
- API Swagger 설명 추가
-
-
- close #
=> Glue 313 Feat: Kylo 개발자가 구현한 API Swagger 설명 추가

src/main/java/com/justdo/plug/post/domain/post/dto/PreviewResponse.java
- 구독 관련 DTO 블로그 정보 추가 전달
-
-
- close #
=> Fix: 구독 관련 DTO 블로그 정보 추가 전달

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java
=> Chore: 전체 게시글 조회 API 네이밍 수정

Dockerfile, src/main/java/com/justdo/plug/post/domain/comment/dto/CommentResponse.java
- dockerfile & comment 작성시간 수정
-
-
- close #
=> fix: dockerfile & comment 작성시간 수정

build.gradle, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/posthashtag/service/PostHashtagService.java, src/main/java/com/justdo/plug/post/domain/recommend/Recommend.java, src/main/java/com/justdo/plug/post/domain/recommend/RecommendClient.java
- 기존 Recommend Service 와 Openfeign 연결하도록 수정하였습니다.
- 기타 메모리 최적화 시도
- CPU, Memory 최적화를 위해 쿼리 수정하였습니다. 
- 최적화 된 결과는 그라파나로 모니터링 후 확인 예정
-
- close #
=> GLUE-359/ recommend Openfeign 연결, 쿼리 최적화

src/main/java/com/justdo/plug/post/domain/post/dto/SearchResponse.java
- Post 검색 pagination hasNext 추가
- 게시글 검색시 response에 hasNext 추가
- 페이지네이션 수정
- close #
=> GLUE-269/ Post Search Pagination hasnext 추가

README.md
=> Post Search hasNext 추가

src/main/java/com/justdo/plug/post/domain/post/dto/SearchResponse.java
- BlogItem hasnext 추가
-
-
- close #
=> BlogItem hasnext 추가

src/main/java/com/justdo/plug/post/domain/post/dto/PostResponse.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
- Sticker Response DTO 수정
-
-
- [close #](https://github.com/DoTheZ-Team/post-service/pull/66)
=> Sticker Response DTO 수정

src/main/java/com/justdo/plug/post/domain/blog/BlogClient.java, src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostResponse.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java, src/main/java/com/justdo/plug/post/domain/sticker/PostStickerDTO.java, src/main/java/com/justdo/plug/post/domain/sticker/PostStickerResponseDTO.java, src/main/java/com/justdo/plug/post/domain/sticker/StickerClient.java
=> Merge Pull

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostResponse.java
=> Merge: Main merge (post 작성 응답값 수정)

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/SearchResponse.java, src/main/java/com/justdo/plug/post/domain/sticker/PostStickerDTO.java
- Blog Info 반환값 수정
@yeyounging 
- 
-
- close #
=> BLOG info 수정

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostResponse.java
=> Blog Info 수정 Main Merge

src/main/java/com/justdo/plug/post/domain/post/controller/PostController.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
- 로그인 없이 포스트 조회 가능
- 기존 포스트 작성자 닉네임 반환으로 변경
- 로그인 없이 null처리
-
- close #
=> GLUE-374/post memberId 수정 및 jwt token null 처리

src/main/java/com/justdo/plug/post/domain/blog/BlogClient.java, src/main/java/com/justdo/plug/post/domain/blog/SubscriptionRequest.java, src/main/java/com/justdo/plug/post/domain/blog/SubscriptionResponse.java, src/main/java/com/justdo/plug/post/domain/post/dto/PostResponse.java, src/main/java/com/justdo/plug/post/domain/post/service/PostService.java
- postResponesDTO 수정 -> blog profile 추가
- profile 값 참고
-
- close #
=> GLUE-382/post Response에 member profile 추가

src/main/java/com/justdo/plug/post/domain/post/dto/SearchResponse.java, src/main/java/com/justdo/plug/post/elastic/PostDocument.java
=> fix: search dto 수정
